{{- if .Values.containerVulnerabilityJob.enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: container-vulnerabilities-job
spec:
  schedule: "{{ .Values.containerVulnerabilityJob.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: container-vulnerabilities
            image: {{ .Values.jobImage.repository }}:{{ .Values.jobImage.tag }}
            imagePullPolicy: {{ .Values.jobImage.pullPolicy }}
            workingDir: /app/container-vulnerabilities
            args:
              - run.sh
            env:
            - name: lwKeyId
              valueFrom:
                secretKeyRef:
                  name: lacework-api-key
                  key: keyId
            - name: lwSecret
              valueFrom:
                secretKeyRef:
                  name: lacework-api-key
                  key: secret
            - name: lwAccount
              valueFrom:
                secretKeyRef:
                  name: lacework-api-key
                  key: account
            - name: lwDataDirectory
              value: /data/container-vulnerabilities
            - name: lwTmpWorkDirectory
              value: /tmp/host-vulnerabilities
            - name: lwMetricsEndpoint
              value: http://opentelemetry-collector:4318
            - name: lwAttributeFilter
              value: "{{ .Values.containerVulnerabilityJob.attributeFilter }}"
            - name: lwStoreExecutionLogs
              value: "{{ .Values.hostVulnerabilityJob.storeExecutionLogs }}"
            volumeMounts:
            - name: data-volume
              mountPath: /data
          restartPolicy: OnFailure
          volumes:
          - name: data-volume
            persistentVolumeClaim:
              claimName: shared-storage
      backoffLimit: 5
{{- end }}
