{{- if .Values.helloWorldJob.enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-world-job
spec:
  schedule: "{{ .Values.helloWorldJob.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello-world
            image: {{ .Values.jobImage.repository }}:{{ .Values.jobImage.tag }}
            imagePullPolicy: {{ .Values.jobImage.pullPolicy }}
            workingDir: /app/helloworld
            args:
              - helloworld.sh
            env:
            - name: lwKeyId
              valueFrom:
                secretKeyRef:
                  name: lacework-api-key
                  key: keyId
            - name: lwSecret
              valueFrom:
                secretKeyRef:
                  name: lacework-api-key
                  key: secret
            - name: lwAccount
              valueFrom:
                secretKeyRef:
                  name: lacework-api-key
                  key: account
            - name: lwDataDirectory
              value: /data/helloworld
            - name: lwTmpWorkDirectory
              value: /tmp/helloworld
            - name: lwMetricsEndpoint
              value: http://opentelemetry-collector:4318
            - name: lwSecondsPauseAferRun
              value: "{{ .Values.helloWorldJob.secondsPauseAferRun }}"
            volumeMounts:
            - name: data-volume
              mountPath: /data
          restartPolicy: OnFailure
          volumes:
          - name: data-volume
            persistentVolumeClaim:
              claimName: shared-storage
      backoffLimit: 5
{{- end }}
