apiVersion: v1
kind: ConfigMap
metadata:
  name: opentelemetry-collector-config
data:
  opentelemetry-collector-config.yml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      batch:
    exporters:
      logging:
        loglevel: debug
{{ if .Values.prometheusGrafana.enabled }}
      otlphttp/prometheus:
        endpoint: "http://prometheus:9090/api/v1/otlp"
        tls:
          insecure: true
{{ end }}
{{ if .Values.opentelemetryCollector.externalOltpEnabled }}
      otlp:
        endpoint: "{{ .Values.opentelemetryCollector.oltpEndpoint }}"
        tls:
          insecure: {{ .Values.opentelemetryCollector.tlsInsecure }}
{{ end }}
    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging{{- if .Values.prometheusGrafana.enabled -}}, otlphttp/prometheus{{- end -}}{{- if .Values.opentelemetryCollector.externalOltpEnabled -}}, otlp{{- end -}}]

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: opentelemetry-collector
  name: opentelemetry-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opentelemetry-collector
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: opentelemetry-collector
    spec:
      containers:
      - image: otel/opentelemetry-collector-contrib:latest
        name: opentelemetry-collector-contrib
        imagePullPolicy: "IfNotPresent"
        args:
          - --config=/conf/opentelemetry-collector-config.yml
        ports:
          - name: metrics
            containerPort: 8888
            protocol: TCP
          - name: otlp
            containerPort: 4317
            protocol: TCP
          - name: otlp-http
            containerPort: 4318
            protocol: TCP        
        env:
          - name: GOMEMLIMIT
            value: 160MiB
        livenessProbe:
          httpGet:
            path: /metrics
            port: 8888
        readinessProbe:
          httpGet:
            path: /metrics
            port: 8888
        resources:
          limits:
            memory: 200Mi
        volumeMounts:
          - mountPath: /conf
            name: config-volume
      volumes:
        - name: config-volume
          configMap:
            name: opentelemetry-collector-config
---
#kubectl port-forward service/opentelemetry-collector 8888:8888
apiVersion: v1
kind: Service
metadata:
  name: opentelemetry-collector
spec:
  selector:
    app: opentelemetry-collector
  ports:
    - name: metrics
      protocol: TCP
      port: 8888
      targetPort: 8888
    - name: oltp
      protocol: TCP
      port: 4317
      targetPort: 4317
    - name: oltp-http
      protocol: TCP
      port: 4318
      targetPort: 4318
