apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-world-job
spec:
# Once an hour
#  schedule: "0 * * * *"
# Once a minute
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello-world
            image: bjornboelacework/opentelemetry-extractor:0.1
            imagePullPolicy: "Always"
            workingDir: /app/helloworld
            args:
              - helloworld.sh
            env:
            - name: lwKeyId
              valueFrom:
                secretKeyRef:
                  name: lacework-api-key
                  key: lwKeyId
            - name: lwSecret
              valueFrom:
                secretKeyRef:
                  name: lacework-api-key
                  key: lwSecret
            - name: lwAccount
              valueFrom:
                secretKeyRef:
                  name: lacework-api-key
                  key: lwAccount
            - name: lwDataDirectory
              value: /data/helloworld
            - name: lwMetricsEndpoint
              value: http://opentelemetry-collector:4318
            volumeMounts:
            - name: data-volume
              mountPath: /data
          restartPolicy: OnFailure
          volumes:
          - name: data-volume
            persistentVolumeClaim:
              claimName: shared-storage
      backoffLimit: 5
